Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2019-04, with the labels that each got.

#38 Retry if StorageClass not found
  controller/controller.go
  controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#39 Remove glog remnants
  .Gopkg.toml
  examples/hostpath-provisioner/Gopkg.toml
  examples/hostpath-provisioner/hostpath-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#37 Simplify storage class properties getters
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#40 Make finalizer optional
  controller/controller.go
  controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#41 Cherry-pick #40 on release-1.14
  controller/controller.go
  controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
