Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2019-01, with the labels that each got.

#6 fixes #5, add a finalizer to fix deletion during pv protection
  controller/controller.go
  controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#16 Allow exponential backoff to save PVs to API server
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#13 Allow disabling of failure thresholds
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S
