Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2020-01, with the labels that each got.

#60 Correctly detect selected node in K8s 1.11 cluster
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#62 Remove Brad Childs from OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Change so that provisioners 'shouldDelete' a volume if it is 'migrated-to' the provisioner in question
  controller/controller.go
  controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
