Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2020-10, with the labels that each got.

#93 Stop linking to deprecated external-storage and creating infinite loop
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 We can't add a volume by Key but volume object directly
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#94 build: update to klog/v2
  controller/controller.go
  controller/controller_test.go
  controller/volume_store.go
  examples/hostpath-provisioner/go.mod
  examples/hostpath-provisioner/go.sum
  examples/hostpath-provisioner/hostpath-provisioner.go
  gidallocator/gidallocator.go
  go.mod
  go.sum
  util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#92 controller: ignore deleted PVs
  controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#98 Cleanup aliases to glog
  controller/controller.go
  controller/controller_test.go
  controller/volume_store.go
  examples/hostpath-provisioner/hostpath-provisioner.go
  gidallocator/gidallocator.go
  util/util.go
Labels: approved, cncf-cla: yes, hacktoberfest-accepted, lgtm, ok-to-test, size/L
