Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2021-06, with the labels that each got.

#106 Remove support for obsolete kubernetes versions
  controller/controller.go
  controller/controller_test.go
  examples/hostpath-provisioner/hostpath-provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#104 Set provision-by anno to the storage class provisioner
  controller/controller.go
  controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#108 Release v7.0.0
  allocator/doc.go
  controller/controller.go
  controller/controller_test.go
  controller/doc.go
  examples/hostpath-provisioner/go.mod
  examples/hostpath-provisioner/hostpath-provisioner.go
  gidallocator/doc.go
  gidallocator/gidallocator.go
  go.mod
  mount/doc.go
  util/doc.go
  v6/README.md
  v6/allocator/doc.go
  v6/allocator/minmax.go
  v6/allocator/minmax_test.go
  v6/controller/controller.go
  v6/controller/controller_test.go
  v6/controller/doc.go
  v6/controller/metrics/doc.go
  v6/controller/metrics/metrics.go
  v6/controller/volume.go
  v6/controller/volume_store.go
  v6/gidallocator/doc.go
  v6/gidallocator/gidallocator.go
  v6/mount/LICENSE
  v6/mount/doc.go
  v6/mount/mount.go
  v6/mount/mountinfo.go
  v6/mount/mountinfo_linux.go
  v6/mount/mountinfo_unsupported.go
  v6/util/doc.go
  v6/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#109 Fix module path to include /v7 suffix
  allocator/doc.go
  controller/controller.go
  controller/controller_test.go
  controller/doc.go
  controller/metrics/doc.go
  examples/hostpath-provisioner/go.mod
  examples/hostpath-provisioner/go.sum
  examples/hostpath-provisioner/hostpath-provisioner.go
  gidallocator/doc.go
  gidallocator/gidallocator.go
  go.mod
  go.sum
  mount/doc.go
  util/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/M
