Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2022-11, with the labels that each got.

#131 Remove reference for glusterfs in-tree plugin driver from README
  README.md
Labels: approved, cncf-cla: yes, size/XS, lgtm, ok-to-test

#125 do not delete the pv in the indexer cache store directly
  controller/controller.go
Labels: approved, cncf-cla: yes, lifecycle/stale, size/XS, lgtm, ok-to-test

#129 Support adding external finalizer for static provisioned volumes
  controller/controller.go
  controller/controller_test.go
Labels: approved, size/L, cncf-cla: yes, lgtm
