Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2024-04, with the labels that each got.

#164 use patch method instead when update finalizer to PV
  controller/controller.go
  examples/hostpath-provisioner/rbac.yaml
Labels: approved, size/M, cncf-cla: yes, lgtm

#167 Update to Kubernetes 1.30
  Makefile
  controller/controller_test.go
  examples/hostpath-provisioner/go.mod
  examples/hostpath-provisioner/go.sum
  go.mod
  go.sum
  repo-infra/verify/README.md
  repo-infra/verify/boilerplate/boilerplate_test.py
  repo-infra/verify/go-tools/verify-gometalinter.sh
Labels: size/XXL, approved, cncf-cla: yes, lgtm

#154 Support structured and contextual logging
  Makefile
  controller/controller.go
  controller/controller_test.go
  controller/volume_store.go
  examples/hostpath-provisioner/go.mod
  examples/hostpath-provisioner/go.sum
  examples/hostpath-provisioner/hostpath-provisioner.go
  gidallocator/gidallocator.go
  hack/verify-logcheck.sh
  util/util.go
Labels: kind/feature, size/XXL, approved, cncf-cla: yes, lgtm

#145 Set log level for k8log.Info calls
  controller/controller.go
  controller/volume_store.go
Labels: approved, size/S, cncf-cla: yes, lgtm, ok-to-test

#170 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/M, cncf-cla: yes, lgtm

#169 Add changelog for v10
  CHANGELOG/CHANGELOG-10.0.md
Labels: approved, size/L, cncf-cla: yes, lgtm
