Repository kubernetes-sigs/sig-storage-lib-external-provisioner, pull requests merged in 2025-09, with the labels that each got.

#195 Add changelog for v12.0.0
  CHANGELOG/CHANGELOG-12.0.md
Labels: kind/documentation, approved, size/L, cncf-cla: yes, lgtm

#196 Update to v12
  allocator/doc.go
  controller/controller.go
  controller/controller_test.go
  controller/doc.go
  controller/metrics/doc.go
  examples/hostpath-provisioner/hostpath-provisioner.go
  gidallocator/doc.go
  gidallocator/gidallocator.go
  go.mod
  mount/doc.go
  util/doc.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm

#197 Add changelog for v12.0.1
  CHANGELOG/CHANGELOG-12.0.md
Labels: kind/documentation, approved, cncf-cla: yes, size/XS, lgtm
